// Generated from the bundled OCRE records and one official Nomisma aggregate RDF snapshot.
export const RIC_PEOPLE_SOURCE = Object.freeze({
  endpoint: "https://nomisma.org/apis/getRdf",
  snapshotSha256: "0619ff8f2bd3d1c6fc58d08a3cc77a5dce443631fad2cb81f42375198675253e",
  generatedOn: "2026-09-15",
  license: "CC-BY-3.0",
  licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
  referencedConceptCount: 272,
  personCount: 214,
  excludedNonPersonCount: 58,
  excludedMissingLabelCount: 0,
  missingConceptCount: 0,
});

export const RIC_PEOPLE = Object.freeze([
  Object.freeze({ id: "aelia_ariadne", name: "Aelia Ariadne", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Ariadna"]) }),
  Object.freeze({ id: "aelia_eudocia", name: "Aelia Eudocia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_eudoxia", name: "Aelia Eudoxia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_flacilla", name: "Aelia Flacilla", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_pulcheria", name: "Aelia Pulcheria", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_verina", name: "Aelia Verina", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aemilian", name: "Aemilian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Aemilianus", "Marcus Aemilius Aemilianus"]) }),
  Object.freeze({ id: "agrippa", name: "Agrippa", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Marcus Vipsanius Agrippa"]) }),
  Object.freeze({ id: "agrippina_i", name: "Agrippina the Elder", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Vipsania Agrippina"]) }),
  Object.freeze({ id: "agrippina_ii", name: "Agrippina the Younger", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["Agrippina minor", "Iulia Agrippina"]) }),
  Object.freeze({ id: "allectus", name: "Allectus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "amandus", name: "Amandus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "annia_faustina", name: "Anna Faustina", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "anonymous", name: "Anonymous", volumes: Object.freeze(["I (2nd edition)", "II", "V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "anthemius", name: "Anthemius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "antonia_minor", name: "Antonia Minor", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["Antonia Augusta", "Antonia minor"]) }),
  Object.freeze({ id: "antoninus_pius", name: "Antoninus Pius", volumes: Object.freeze(["II, Part 3 (2nd edition)", "III", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aquilia_severa", name: "Aquilia Severa", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "arcadius", name: "Arcadius", volumes: Object.freeze(["IX", "X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aretas_iv", name: "Aretas IV of Nabataea", volumes: Object.freeze(["II"]), aliases: Object.freeze(["Aretas IV Philopatris"]) }),
  Object.freeze({ id: "augustus", name: "Augustus", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aurelian", name: "Aurelian", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Aurelianus"]) }),
  Object.freeze({ id: "aureolus", name: "Aureolus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Manius Acilius Aureolus"]) }),
  Object.freeze({ id: "avitus", name: "Avitus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "balbinus", name: "Balbinus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "basiliscus", name: "Basiliscus", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Flavius Basiliscus"]) }),
  Object.freeze({ id: "bonosus", name: "Bonosus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "caecilia_paulina", name: "Caecilla Paulina", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Caecilia Paulina"]) }),
  Object.freeze({ id: "caracalla", name: "Caracalla", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "carausius", name: "Carausius", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "carinus", name: "Carinus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "carus", name: "Carus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Aurelius Carus"]) }),
  Object.freeze({ id: "claudius", name: "Claudius", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "claudius_ii_gothicus", name: "Claudius II Gothicus", volumes: Object.freeze(["V", "VII"]), aliases: Object.freeze(["Claudius Gothicus"]) }),
  Object.freeze({ id: "clodius_albinus", name: "Clodius Albinus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Decimus Clodius Septimius Albinus"]) }),
  Object.freeze({ id: "clodius_macer", name: "Clodius Macer", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["Lucius Clodius Macer"]) }),
  Object.freeze({ id: "commodus", name: "Commodus", volumes: Object.freeze(["III", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constans", name: "Constans", volumes: Object.freeze(["VII", "VIII", "X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantine_i", name: "Constantine I", volumes: Object.freeze(["V", "VI", "VII", "VIII"]), aliases: Object.freeze(["Constantinus I"]) }),
  Object.freeze({ id: "constantine_ii", name: "Constantine II", volumes: Object.freeze(["VII", "VIII"]), aliases: Object.freeze(["Constantinus II", "Constantinus II."]) }),
  Object.freeze({ id: "constantine_iii", name: "Constantine III", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Constantinus III"]) }),
  Object.freeze({ id: "constantius_chlorus", name: "Constantius Chlorus", volumes: Object.freeze(["V", "VI", "VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantius_gallus", name: "Constantius Gallus", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantius_ii", name: "Constantius II", volumes: Object.freeze(["VII", "VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantius_iii", name: "Constantius III", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "cornelia_salonina", name: "Cornelia Salonina", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Salonina"]) }),
  Object.freeze({ id: "cornelia_supera", name: "Cornelia Supera", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "crispina", name: "Crispina", volumes: Object.freeze(["III"]), aliases: Object.freeze(["Bruttia Crispina"]) }),
  Object.freeze({ id: "crispus", name: "Crispus", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["Flavius Iulius Crispus"]) }),
  Object.freeze({ id: "dalmatius", name: "Dalmatius", volumes: Object.freeze(["VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "decentius", name: "Decentius", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "diadumenian", name: "Diadumenian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Diadumenianus"]) }),
  Object.freeze({ id: "didia_clara", name: "Didia Clara", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "didius_julianus", name: "Didius Julianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Marcus Didius Iulianus", "Marcus Didius Severus Julianus"]) }),
  Object.freeze({ id: "diocletian", name: "Diocletian", volumes: Object.freeze(["V", "VI"]), aliases: Object.freeze(["Diocletianus"]) }),
  Object.freeze({ id: "domitia", name: "Domitia", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Domitia Longina"]) }),
  Object.freeze({ id: "domitian", name: "Domitian", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "domitian_ii", name: "Domitian II", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Domitian of Gaul", "Domitianus"]) }),
  Object.freeze({ id: "domitilla_the_elder", name: "Domitilla the Elder", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Flavia Domitilla"]) }),
  Object.freeze({ id: "domitius_alexander", name: "Domitius Alexander", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "domitius_domitianus", name: "Domitius Domitianus", volumes: Object.freeze(["VI"]), aliases: Object.freeze(["Lucius Domitius Domitianus"]) }),
  Object.freeze({ id: "drusus_caesar", name: "Drusus Caesar", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Drusus Iulius Caesar"]) }),
  Object.freeze({ id: "drusus_son_of_tiberius", name: "Drusus the Younger", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["Drusus Iulius Caesar", "Drusus Julius Caesar"]) }),
  Object.freeze({ id: "dryantilla", name: "Dryantilla", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Sulpicia Dryantilla"]) }),
  Object.freeze({ id: "egnatia_mariniana", name: "Egnatia Mariniana", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "elagabalus", name: "Elagabalus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "eugenius", name: "Eugenius", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "euphemia", name: "Euphemia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "fausta", name: "Fausta", volumes: Object.freeze(["VI", "VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "faustina_i", name: "Faustina the Elder", volumes: Object.freeze(["III"]), aliases: Object.freeze(["Annia Galeria Faustina"]) }),
  Object.freeze({ id: "faustina_ii", name: "Faustina the Younger", volumes: Object.freeze(["III"]), aliases: Object.freeze(["Annia Galeria Faustina Minor"]) }),
  Object.freeze({ id: "flavia_iulia_constantia", name: "Flavia Iulia Constantia", volumes: Object.freeze(["VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "flavius_marcus", name: "Flavius Marcus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "flavius_victor", name: "Flavius Victor", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "florianus", name: "Florianus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Annius Florianus"]) }),
  Object.freeze({ id: "gaius", name: "Gaius/Caligula", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "gaius_julius_verus_maximus", name: "Maximus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Gaius Julius Verus Maximus"]) }),
  Object.freeze({ id: "galba", name: "Galba", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Servius Sulpicius Galba"]) }),
  Object.freeze({ id: "galeria_valeria", name: "Galeria Valeria", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "galerius", name: "Galerius", volumes: Object.freeze(["V", "VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "galla_placidia", name: "Galla Placidia", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Aelia Galla Placidia"]) }),
  Object.freeze({ id: "gallienus", name: "Gallienus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Publius Licinius Egnatius Gallienus"]) }),
  Object.freeze({ id: "germanicus", name: "Germanicus", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Germanicus Julius Caesar"]) }),
  Object.freeze({ id: "geta", name: "Geta", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "glycerius", name: "Glycerius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "gordian_i", name: "Gordian I", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Gordianus I"]) }),
  Object.freeze({ id: "gordian_ii", name: "Gordian II", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Gordianus II"]) }),
  Object.freeze({ id: "gordian_iii", name: "Gordian III", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Gordianus III"]) }),
  Object.freeze({ id: "grata_honoria", name: "Grata Honoria", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Iusta Grata Honoria"]) }),
  Object.freeze({ id: "gratian", name: "Gratian", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["Gratianus"]) }),
  Object.freeze({ id: "hadrian", name: "Hadrian", volumes: Object.freeze(["II", "II, Part 3 (2nd edition)", "IV"]), aliases: Object.freeze(["Hadrianus"]) }),
  Object.freeze({ id: "hannibalianus", name: "Hannibalianus", volumes: Object.freeze(["VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "helena", name: "Helena", volumes: Object.freeze(["VII", "VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "herennia_etruscilla", name: "Herennia Etruscilla", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Herennia Cupressenia Etruscilla"]) }),
  Object.freeze({ id: "herennius_etruscus", name: "Herennius Etruscus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "honorius", name: "Honorius", volumes: Object.freeze(["IX", "X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "hostilian", name: "Hostilian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Hostilianus"]) }),
  Object.freeze({ id: "joannes", name: "Joannes", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Ioannes"]) }),
  Object.freeze({ id: "jotapianus", name: "Jotapianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Marcus F. Ru. Jotapianus", "Marcus Fulvius Ru"]) }),
  Object.freeze({ id: "jovianus", name: "Jovianus", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["Iovianus"]) }),
  Object.freeze({ id: "jovinus", name: "Jovinus", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Iovinus"]) }),
  Object.freeze({ id: "julia_domna", name: "Julia Domna", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Iulia Domna"]) }),
  Object.freeze({ id: "julia_maesa", name: "Julia Maesa", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Iulia Maesa"]) }),
  Object.freeze({ id: "julia_mamaea", name: "Julia Mamaea", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Iulia Mamaea"]) }),
  Object.freeze({ id: "julia_paula", name: "Julia Paula", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "julia_soaemias", name: "Julia Soaemias", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Iulia Soaemias"]) }),
  Object.freeze({ id: "julia_titi", name: "Julia Titi", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Flavia Iulia Titi"]) }),
  Object.freeze({ id: "julian_the_apostate", name: "Julian the Apostate", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["Flavius Claudius Iulianus"]) }),
  Object.freeze({ id: "julius_caesar", name: "Julius Caesar", volumes: Object.freeze(["II"]), aliases: Object.freeze(["Gaius Iulius Caesar"]) }),
  Object.freeze({ id: "julius_nepos", name: "Julius Nepos", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Iulius Nepos"]) }),
  Object.freeze({ id: "laelianus", name: "Laelianus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Ulpius Cornelius Laelianus"]) }),
  Object.freeze({ id: "leo_i", name: "Leo I", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "leo_ii", name: "Leo II", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "leontius", name: "Leontius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "libius_severus", name: "Libius Severus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "licinia_eudoxia", name: "Licinia Eudoxia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "licinius", name: "Licinius", volumes: Object.freeze(["VI", "VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "licinius_ii", name: "Licinius II", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["Valerius Licinianus Licinius"]) }),
  Object.freeze({ id: "livia", name: "Livia", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Livia Drusilla"]) }),
  Object.freeze({ id: "lucilla", name: "Lucilla", volumes: Object.freeze(["III"]), aliases: Object.freeze(["Annia Aurelia Galeria Lucilla"]) }),
  Object.freeze({ id: "lucius_aelius", name: "Lucius Aelius", volumes: Object.freeze(["II, Part 3 (2nd edition)"]), aliases: Object.freeze(["Lucius Aelius Caesar"]) }),
  Object.freeze({ id: "lucius_verus", name: "Lucius Verus", volumes: Object.freeze(["III"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "macrianus_minor", name: "Macrianus Minor", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Titus Fulvius Macrianus"]) }),
  Object.freeze({ id: "macrinus", name: "Macrinus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "magnentius", name: "Magnentius", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "magnia_urbica", name: "Magnia Urbica", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "magnus_maximus", name: "Magnus Maximus", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "majorian", name: "Majorian", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Maiorianus"]) }),
  Object.freeze({ id: "manlia_scantilla", name: "Manlia Scantilla", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "mar_silbannacus", name: "Mar. Silbannacus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "marcian", name: "Marcian", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Marcianus"]) }),
  Object.freeze({ id: "marciana", name: "Marciana", volumes: Object.freeze(["II"]), aliases: Object.freeze(["Ulpia Marciana"]) }),
  Object.freeze({ id: "marcus_aurelius", name: "Marcus Aurelius", volumes: Object.freeze(["III", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "marcus_claudius_marcellus", name: "Marcellus", volumes: Object.freeze(["II"]), aliases: Object.freeze(["Marcus Claudius Marcellus"]) }),
  Object.freeze({ id: "marius", name: "Marius", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Aurelius Marius"]) }),
  Object.freeze({ id: "matidia", name: "Matidia", volumes: Object.freeze(["II, Part 3 (2nd edition)"]), aliases: Object.freeze(["Salonina Matidia"]) }),
  Object.freeze({ id: "maxentius", name: "Maxentius", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "maximian", name: "Maximian", volumes: Object.freeze(["V", "VI", "VII"]), aliases: Object.freeze(["Maximianus"]) }),
  Object.freeze({ id: "maximinus_daia", name: "Maximinus Daia", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "maximinus_thrax", name: "Maximinus Thrax", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "maximus_barcelona", name: "Maximus of Barcelona", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Maximus"]) }),
  Object.freeze({ id: "messallina", name: "Messalina", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["Valeria Messalina"]) }),
  Object.freeze({ id: "nepotianus", name: "Nepotianus", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["Flavius Popilius Virius Nepotianus"]) }),
  Object.freeze({ id: "nero", name: "Nero", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "nero_claudius_drusus", name: "Drusus the Elder", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["Nero Claudius Drusus", "Nero Claudius Drusus Germanicus"]) }),
  Object.freeze({ id: "nerva", name: "Nerva", volumes: Object.freeze(["II", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "nigrinian", name: "Nigrinian", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "numerian", name: "Numerian", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Numerianus"]) }),
  Object.freeze({ id: "octavian", name: "Octavian", volumes: Object.freeze(["I (2nd edition)", "II"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "odoacer", name: "Odoacer", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "olybrius", name: "Olybrius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "otacilia_severa", name: "Otacilia Severa", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "otho", name: "Otho", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "pacatianus", name: "Pacatianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Tiberius Claudius Marinus Pacatianus"]) }),
  Object.freeze({ id: "pertinax", name: "Pertinax", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Publius Helvius Pertinax"]) }),
  Object.freeze({ id: "pescennius_niger", name: "Pescennius Niger", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Gaius Pescennius Niger"]) }),
  Object.freeze({ id: "petronius_maximus", name: "Petronius Maximus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "philip_the_arab", name: "Philip the Arab", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Philippus Arabs"]) }),
  Object.freeze({ id: "philippus_ii", name: "Philip II", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Philip the Younger", "Philippus II"]) }),
  Object.freeze({ id: "plautilla", name: "Plautilla", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "plotina", name: "Plotina", volumes: Object.freeze(["II", "II, Part 3 (2nd edition)"]), aliases: Object.freeze(["Pompeia Plotina"]) }),
  Object.freeze({ id: "pompey", name: "Pompey", volumes: Object.freeze(["II"]), aliases: Object.freeze(["Gnaeus Pompeius Magnus"]) }),
  Object.freeze({ id: "postumus", name: "Postumus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Cassianus Latinius Postumus"]) }),
  Object.freeze({ id: "priscus_attalus", name: "Priscus Attalus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "probus", name: "Probus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Aurelius Probus"]) }),
  Object.freeze({ id: "procopius", name: "Procopius", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "pupienus", name: "Pupienus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Marcus Clodius Pupienus Maximus"]) }),
  Object.freeze({ id: "quietus", name: "Quietus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Titus Iunius Fulvius Quietus"]) }),
  Object.freeze({ id: "quintillus", name: "Quintillus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "quintus_julius_gallienus", name: "Quintus Julius Gallienus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "regalianus", name: "Regalianus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "romulus", name: "Romulus", volumes: Object.freeze(["II", "VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "romulus_augustulus", name: "Romulus Augustulus", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Flavius Romulus"]) }),
  Object.freeze({ id: "sabina", name: "Sabina", volumes: Object.freeze(["II, Part 3 (2nd edition)"]), aliases: Object.freeze(["Vibia Sabina"]) }),
  Object.freeze({ id: "sabinia_tranquillina", name: "Sabinia Tranquillina", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "sabinus_julianus", name: "Julian of Pannonia", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Aurelius Iulianus", "Marcus Aurelius Julianus", "Sabinus Julianus"]) }),
  Object.freeze({ id: "sallustia_orbiana", name: "Sallustia Orbiana", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "saloninus", name: "Saloninus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "saturninus", name: "Saturninus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Sextus"]) }),
  Object.freeze({ id: "sebastianus", name: "Sebastianus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "septimius_severus", name: "Septimius Severus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "severus_alexander", name: "Severus Alexander", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Alexander Severus"]) }),
  Object.freeze({ id: "severus_ii", name: "Severus II", volumes: Object.freeze(["VI"]), aliases: Object.freeze(["Flavius Valerius Severus"]) }),
  Object.freeze({ id: "sextus_martinianus", name: "Martinianus", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["Sextus Marcius Martinianus"]) }),
  Object.freeze({ id: "sponsianus", name: "Sponsianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "sulla", name: "Sulla", volumes: Object.freeze(["II"]), aliases: Object.freeze(["Lucius Cornelius Sulla", "Lucius Cornelius Sulla Felix"]) }),
  Object.freeze({ id: "tacitus", name: "Tacitus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Marcus Claudius Tacitus"]) }),
  Object.freeze({ id: "tetricus_i", name: "Tetricus I", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "tetricus_ii", name: "Tetricus II", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "theodora", name: "Theodora", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["Flavia Maximiana Theodora"]) }),
  Object.freeze({ id: "theodosius_i", name: "Theodosius I", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "theodosius_ii", name: "Theodosius II", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "tiberius", name: "Tiberius", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "titus", name: "Titus", volumes: Object.freeze(["II", "II, Part 1 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "trajan", name: "Trajan", volumes: Object.freeze(["II", "II, Part 3 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "trajan_decius", name: "Trajan Decius", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Decius"]) }),
  Object.freeze({ id: "trebonianus_gallus", name: "Trebonianus Gallus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "ulpia_severina", name: "Ulpia Severina", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "uranius_antoninus", name: "Uranius Antoninus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "vabalathus", name: "Vabalathus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Lucius Iulius Septimius Vaballatus Aphenodorus"]) }),
  Object.freeze({ id: "valens", name: "Valens", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["Flavius Valens"]) }),
  Object.freeze({ id: "valentinian_i", name: "Valentinian I", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["Valentinianus I"]) }),
  Object.freeze({ id: "valentinian_ii", name: "Valentinian II", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["Valentinianus II"]) }),
  Object.freeze({ id: "valentinian_iii", name: "Valentinian III", volumes: Object.freeze(["X"]), aliases: Object.freeze(["Valentinianus III"]) }),
  Object.freeze({ id: "valerian", name: "Valerian", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Valerianus"]) }),
  Object.freeze({ id: "valerian_ii", name: "Valerian II", volumes: Object.freeze(["V"]), aliases: Object.freeze(["Valerianus"]) }),
  Object.freeze({ id: "valerius_valens", name: "Valerius Valens", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["Aurelius Valerius Valens"]) }),
  Object.freeze({ id: "vespasian", name: "Vespasian", volumes: Object.freeze(["II", "II, Part 1 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "vetranio", name: "Vetranio", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "victorinus", name: "Victorinus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "vitellius", name: "Vitellius", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "volusian", name: "Volusian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["Gaius Vibius Volusianus", "Volusianus"]) }),
  Object.freeze({ id: "zeno", name: "Zeno", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "zenobia", name: "Zenobia", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
]);
