// Generated from the bundled OCRE records, one official Nomisma aggregate RDF snapshot and the tracked Nomisma mint snapshot.
// Source:
//   endpoint: "https://nomisma.org/apis/getRdf"
//   snapshotSha256: "0619ff8f2bd3d1c6fc58d08a3cc77a5dce443631fad2cb81f42375198675253e"
//   generatedOn: "2026-09-15"
//   license: "CC-BY-3.0"
//   licenseUrl: "https://creativecommons.org/licenses/by/3.0/"
//   referencedConceptCount: 272
//   personCount: 214
//   excludedNonPersonCount: 58
//   excludedMissingLabelCount: 0
//   missingConceptCount: 0
//   aliasCount: 120
//   mintCount: 8
//   mintAliasCount: 9

export const RIC_PEOPLE = Object.freeze([
  Object.freeze({ id: "aelia_ariadne", name: "Aelia Ariadne", volumes: Object.freeze(["X"]), aliases: Object.freeze(["ariadna"]) }),
  Object.freeze({ id: "aelia_eudocia", name: "Aelia Eudocia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_eudoxia", name: "Aelia Eudoxia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_flacilla", name: "Aelia Flacilla", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_pulcheria", name: "Aelia Pulcheria", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aelia_verina", name: "Aelia Verina", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aemilian", name: "Aemilian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["aemilianus", "marcus aemilius aemilianus"]) }),
  Object.freeze({ id: "agrippa", name: "Agrippa", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["marcus vipsanius agrippa"]) }),
  Object.freeze({ id: "agrippina_i", name: "Agrippina the Elder", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["vipsania agrippina"]) }),
  Object.freeze({ id: "agrippina_ii", name: "Agrippina the Younger", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["agrippina minor", "iulia agrippina"]) }),
  Object.freeze({ id: "allectus", name: "Allectus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "amandus", name: "Amandus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "annia_faustina", name: "Anna Faustina", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "anonymous", name: "Anonymous", volumes: Object.freeze(["I (2nd edition)", "II", "V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "anthemius", name: "Anthemius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "antonia_minor", name: "Antonia Minor", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["antonia augusta"]) }),
  Object.freeze({ id: "antoninus_pius", name: "Antoninus Pius", volumes: Object.freeze(["II, Part 3 (2nd edition)", "III", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aquilia_severa", name: "Aquilia Severa", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "arcadius", name: "Arcadius", volumes: Object.freeze(["IX", "X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aretas_iv", name: "Aretas IV of Nabataea", volumes: Object.freeze(["II"]), aliases: Object.freeze(["aretas iv philopatris"]) }),
  Object.freeze({ id: "augustus", name: "Augustus", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "aurelian", name: "Aurelian", volumes: Object.freeze(["V"]), aliases: Object.freeze(["aurelianus"]) }),
  Object.freeze({ id: "aureolus", name: "Aureolus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["manius acilius aureolus"]) }),
  Object.freeze({ id: "avitus", name: "Avitus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "balbinus", name: "Balbinus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "basiliscus", name: "Basiliscus", volumes: Object.freeze(["X"]), aliases: Object.freeze(["flavius basiliscus"]) }),
  Object.freeze({ id: "bonosus", name: "Bonosus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "caecilia_paulina", name: "Caecilla Paulina", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["caecilia paulina"]) }),
  Object.freeze({ id: "caracalla", name: "Caracalla", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "carausius", name: "Carausius", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "carinus", name: "Carinus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "carus", name: "Carus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus aurelius carus"]) }),
  Object.freeze({ id: "claudius", name: "Claudius", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "claudius_ii_gothicus", name: "Claudius II Gothicus", volumes: Object.freeze(["V", "VII"]), aliases: Object.freeze(["claudius gothicus"]) }),
  Object.freeze({ id: "clodius_albinus", name: "Clodius Albinus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["decimus clodius septimius albinus"]) }),
  Object.freeze({ id: "clodius_macer", name: "Clodius Macer", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["lucius clodius macer"]) }),
  Object.freeze({ id: "commodus", name: "Commodus", volumes: Object.freeze(["III", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constans", name: "Constans", volumes: Object.freeze(["VII", "VIII", "X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantine_i", name: "Constantine I", volumes: Object.freeze(["V", "VI", "VII", "VIII"]), aliases: Object.freeze(["constantinus i"]) }),
  Object.freeze({ id: "constantine_ii", name: "Constantine II", volumes: Object.freeze(["VII", "VIII"]), aliases: Object.freeze(["constantinus ii"]) }),
  Object.freeze({ id: "constantine_iii", name: "Constantine III", volumes: Object.freeze(["X"]), aliases: Object.freeze(["constantinus iii"]) }),
  Object.freeze({ id: "constantius_chlorus", name: "Constantius Chlorus", volumes: Object.freeze(["V", "VI", "VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantius_gallus", name: "Constantius Gallus", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantius_ii", name: "Constantius II", volumes: Object.freeze(["VII", "VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "constantius_iii", name: "Constantius III", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "cornelia_salonina", name: "Cornelia Salonina", volumes: Object.freeze(["V"]), aliases: Object.freeze(["salonina"]) }),
  Object.freeze({ id: "cornelia_supera", name: "Cornelia Supera", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "crispina", name: "Crispina", volumes: Object.freeze(["III"]), aliases: Object.freeze(["bruttia crispina"]) }),
  Object.freeze({ id: "crispus", name: "Crispus", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["flavius iulius crispus"]) }),
  Object.freeze({ id: "dalmatius", name: "Dalmatius", volumes: Object.freeze(["VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "decentius", name: "Decentius", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "diadumenian", name: "Diadumenian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["diadumenianus"]) }),
  Object.freeze({ id: "didia_clara", name: "Didia Clara", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "didius_julianus", name: "Didius Julianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["marcus didius iulianus", "marcus didius severus julianus"]) }),
  Object.freeze({ id: "diocletian", name: "Diocletian", volumes: Object.freeze(["V", "VI"]), aliases: Object.freeze(["diocletianus"]) }),
  Object.freeze({ id: "domitia", name: "Domitia", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["domitia longina"]) }),
  Object.freeze({ id: "domitian", name: "Domitian", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "domitian_ii", name: "Domitian II", volumes: Object.freeze(["V"]), aliases: Object.freeze(["domitian of gaul", "domitianus"]) }),
  Object.freeze({ id: "domitilla_the_elder", name: "Domitilla the Elder", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["flavia domitilla"]) }),
  Object.freeze({ id: "domitius_alexander", name: "Domitius Alexander", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "domitius_domitianus", name: "Domitius Domitianus", volumes: Object.freeze(["VI"]), aliases: Object.freeze(["lucius domitius domitianus"]) }),
  Object.freeze({ id: "drusus_caesar", name: "Drusus Caesar", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["drusus iulius caesar"]) }),
  Object.freeze({ id: "drusus_son_of_tiberius", name: "Drusus the Younger", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["drusus iulius caesar", "drusus julius caesar"]) }),
  Object.freeze({ id: "dryantilla", name: "Dryantilla", volumes: Object.freeze(["V"]), aliases: Object.freeze(["sulpicia dryantilla"]) }),
  Object.freeze({ id: "egnatia_mariniana", name: "Egnatia Mariniana", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "elagabalus", name: "Elagabalus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "eugenius", name: "Eugenius", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "euphemia", name: "Euphemia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "fausta", name: "Fausta", volumes: Object.freeze(["VI", "VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "faustina_i", name: "Faustina the Elder", volumes: Object.freeze(["III"]), aliases: Object.freeze(["annia galeria faustina"]) }),
  Object.freeze({ id: "faustina_ii", name: "Faustina the Younger", volumes: Object.freeze(["III"]), aliases: Object.freeze(["annia galeria faustina minor"]) }),
  Object.freeze({ id: "flavia_iulia_constantia", name: "Flavia Iulia Constantia", volumes: Object.freeze(["VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "flavius_marcus", name: "Flavius Marcus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "flavius_victor", name: "Flavius Victor", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "florianus", name: "Florianus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus annius florianus"]) }),
  Object.freeze({ id: "gaius", name: "Gaius/Caligula", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "gaius_julius_verus_maximus", name: "Maximus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["gaius julius verus maximus"]) }),
  Object.freeze({ id: "galba", name: "Galba", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["servius sulpicius galba"]) }),
  Object.freeze({ id: "galeria_valeria", name: "Galeria Valeria", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "galerius", name: "Galerius", volumes: Object.freeze(["V", "VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "galla_placidia", name: "Galla Placidia", volumes: Object.freeze(["X"]), aliases: Object.freeze(["aelia galla placidia"]) }),
  Object.freeze({ id: "gallienus", name: "Gallienus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["publius licinius egnatius gallienus"]) }),
  Object.freeze({ id: "germanicus", name: "Germanicus", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["germanicus julius caesar"]) }),
  Object.freeze({ id: "geta", name: "Geta", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "glycerius", name: "Glycerius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "gordian_i", name: "Gordian I", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["gordianus i"]) }),
  Object.freeze({ id: "gordian_ii", name: "Gordian II", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["gordianus ii"]) }),
  Object.freeze({ id: "gordian_iii", name: "Gordian III", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["gordianus iii"]) }),
  Object.freeze({ id: "grata_honoria", name: "Grata Honoria", volumes: Object.freeze(["X"]), aliases: Object.freeze(["iusta grata honoria"]) }),
  Object.freeze({ id: "gratian", name: "Gratian", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["gratianus"]) }),
  Object.freeze({ id: "hadrian", name: "Hadrian", volumes: Object.freeze(["II", "II, Part 3 (2nd edition)", "IV"]), aliases: Object.freeze(["hadrianus"]) }),
  Object.freeze({ id: "hannibalianus", name: "Hannibalianus", volumes: Object.freeze(["VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "helena", name: "Helena", volumes: Object.freeze(["VII", "VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "herennia_etruscilla", name: "Herennia Etruscilla", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["herennia cupressenia etruscilla"]) }),
  Object.freeze({ id: "herennius_etruscus", name: "Herennius Etruscus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "honorius", name: "Honorius", volumes: Object.freeze(["IX", "X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "hostilian", name: "Hostilian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["hostilianus"]) }),
  Object.freeze({ id: "joannes", name: "Joannes", volumes: Object.freeze(["X"]), aliases: Object.freeze(["ioannes"]) }),
  Object.freeze({ id: "jotapianus", name: "Jotapianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["marcus f. ru. jotapianus", "marcus fulvius ru"]) }),
  Object.freeze({ id: "jovianus", name: "Jovianus", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["iovianus"]) }),
  Object.freeze({ id: "jovinus", name: "Jovinus", volumes: Object.freeze(["X"]), aliases: Object.freeze(["iovinus"]) }),
  Object.freeze({ id: "julia_domna", name: "Julia Domna", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["iulia domna"]) }),
  Object.freeze({ id: "julia_maesa", name: "Julia Maesa", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["iulia maesa"]) }),
  Object.freeze({ id: "julia_mamaea", name: "Julia Mamaea", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["iulia mamaea"]) }),
  Object.freeze({ id: "julia_paula", name: "Julia Paula", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "julia_soaemias", name: "Julia Soaemias", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["iulia soaemias"]) }),
  Object.freeze({ id: "julia_titi", name: "Julia Titi", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["flavia iulia titi"]) }),
  Object.freeze({ id: "julian_the_apostate", name: "Julian the Apostate", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["flavius claudius iulianus"]) }),
  Object.freeze({ id: "julius_caesar", name: "Julius Caesar", volumes: Object.freeze(["II"]), aliases: Object.freeze(["gaius iulius caesar"]) }),
  Object.freeze({ id: "julius_nepos", name: "Julius Nepos", volumes: Object.freeze(["X"]), aliases: Object.freeze(["iulius nepos"]) }),
  Object.freeze({ id: "laelianus", name: "Laelianus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["ulpius cornelius laelianus"]) }),
  Object.freeze({ id: "leo_i", name: "Leo I", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "leo_ii", name: "Leo II", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "leontius", name: "Leontius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "libius_severus", name: "Libius Severus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "licinia_eudoxia", name: "Licinia Eudoxia", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "licinius", name: "Licinius", volumes: Object.freeze(["VI", "VII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "licinius_ii", name: "Licinius II", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["valerius licinianus licinius"]) }),
  Object.freeze({ id: "livia", name: "Livia", volumes: Object.freeze(["II, Part 1 (2nd edition)"]), aliases: Object.freeze(["livia drusilla"]) }),
  Object.freeze({ id: "lucilla", name: "Lucilla", volumes: Object.freeze(["III"]), aliases: Object.freeze(["annia aurelia galeria lucilla"]) }),
  Object.freeze({ id: "lucius_aelius", name: "Lucius Aelius", volumes: Object.freeze(["II, Part 3 (2nd edition)"]), aliases: Object.freeze(["lucius aelius caesar"]) }),
  Object.freeze({ id: "lucius_verus", name: "Lucius Verus", volumes: Object.freeze(["III"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "macrianus_minor", name: "Macrianus Minor", volumes: Object.freeze(["V"]), aliases: Object.freeze(["titus fulvius macrianus"]) }),
  Object.freeze({ id: "macrinus", name: "Macrinus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "magnentius", name: "Magnentius", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "magnia_urbica", name: "Magnia Urbica", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "magnus_maximus", name: "Magnus Maximus", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "majorian", name: "Majorian", volumes: Object.freeze(["X"]), aliases: Object.freeze(["maiorianus"]) }),
  Object.freeze({ id: "manlia_scantilla", name: "Manlia Scantilla", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "mar_silbannacus", name: "Mar. Silbannacus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "marcian", name: "Marcian", volumes: Object.freeze(["X"]), aliases: Object.freeze(["marcianus"]) }),
  Object.freeze({ id: "marciana", name: "Marciana", volumes: Object.freeze(["II"]), aliases: Object.freeze(["ulpia marciana"]) }),
  Object.freeze({ id: "marcus_aurelius", name: "Marcus Aurelius", volumes: Object.freeze(["III", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "marcus_claudius_marcellus", name: "Marcellus", volumes: Object.freeze(["II"]), aliases: Object.freeze(["marcus claudius marcellus"]) }),
  Object.freeze({ id: "marius", name: "Marius", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus aurelius marius"]) }),
  Object.freeze({ id: "matidia", name: "Matidia", volumes: Object.freeze(["II, Part 3 (2nd edition)"]), aliases: Object.freeze(["salonina matidia"]) }),
  Object.freeze({ id: "maxentius", name: "Maxentius", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "maximian", name: "Maximian", volumes: Object.freeze(["V", "VI", "VII"]), aliases: Object.freeze(["maximianus"]) }),
  Object.freeze({ id: "maximinus_daia", name: "Maximinus Daia", volumes: Object.freeze(["VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "maximinus_thrax", name: "Maximinus Thrax", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "maximus_barcelona", name: "Maximus of Barcelona", volumes: Object.freeze(["X"]), aliases: Object.freeze(["maximus"]) }),
  Object.freeze({ id: "messallina", name: "Messalina", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze(["valeria messalina"]) }),
  Object.freeze({ id: "nepotianus", name: "Nepotianus", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["flavius popilius virius nepotianus"]) }),
  Object.freeze({ id: "nero", name: "Nero", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "nero_claudius_drusus", name: "Drusus the Elder", volumes: Object.freeze(["I (2nd edition)", "II, Part 1 (2nd edition)"]), aliases: Object.freeze(["nero claudius drusus", "nero claudius drusus germanicus"]) }),
  Object.freeze({ id: "nerva", name: "Nerva", volumes: Object.freeze(["II", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "nigrinian", name: "Nigrinian", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "numerian", name: "Numerian", volumes: Object.freeze(["V"]), aliases: Object.freeze(["numerianus"]) }),
  Object.freeze({ id: "octavian", name: "Octavian", volumes: Object.freeze(["I (2nd edition)", "II"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "odoacer", name: "Odoacer", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "olybrius", name: "Olybrius", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "otacilia_severa", name: "Otacilia Severa", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "otho", name: "Otho", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "pacatianus", name: "Pacatianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["tiberius claudius marinus pacatianus"]) }),
  Object.freeze({ id: "pertinax", name: "Pertinax", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["publius helvius pertinax"]) }),
  Object.freeze({ id: "pescennius_niger", name: "Pescennius Niger", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["gaius pescennius niger"]) }),
  Object.freeze({ id: "petronius_maximus", name: "Petronius Maximus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "philip_the_arab", name: "Philip the Arab", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["philippus arabs"]) }),
  Object.freeze({ id: "philippus_ii", name: "Philip II", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["philip the younger", "philippus ii"]) }),
  Object.freeze({ id: "plautilla", name: "Plautilla", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "plotina", name: "Plotina", volumes: Object.freeze(["II", "II, Part 3 (2nd edition)"]), aliases: Object.freeze(["pompeia plotina"]) }),
  Object.freeze({ id: "pompey", name: "Pompey", volumes: Object.freeze(["II"]), aliases: Object.freeze(["gnaeus pompeius magnus"]) }),
  Object.freeze({ id: "postumus", name: "Postumus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus cassianus latinius postumus"]) }),
  Object.freeze({ id: "priscus_attalus", name: "Priscus Attalus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "probus", name: "Probus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus aurelius probus"]) }),
  Object.freeze({ id: "procopius", name: "Procopius", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "pupienus", name: "Pupienus", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["marcus clodius pupienus maximus"]) }),
  Object.freeze({ id: "quietus", name: "Quietus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["titus iunius fulvius quietus"]) }),
  Object.freeze({ id: "quintillus", name: "Quintillus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "quintus_julius_gallienus", name: "Quintus Julius Gallienus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "regalianus", name: "Regalianus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "romulus", name: "Romulus", volumes: Object.freeze(["II", "VI"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "romulus_augustulus", name: "Romulus Augustulus", volumes: Object.freeze(["X"]), aliases: Object.freeze(["flavius romulus"]) }),
  Object.freeze({ id: "sabina", name: "Sabina", volumes: Object.freeze(["II, Part 3 (2nd edition)"]), aliases: Object.freeze(["vibia sabina"]) }),
  Object.freeze({ id: "sabinia_tranquillina", name: "Sabinia Tranquillina", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "sabinus_julianus", name: "Julian of Pannonia", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus aurelius iulianus", "marcus aurelius julianus", "sabinus julianus"]) }),
  Object.freeze({ id: "sallustia_orbiana", name: "Sallustia Orbiana", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "saloninus", name: "Saloninus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "saturninus", name: "Saturninus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["sextus"]) }),
  Object.freeze({ id: "sebastianus", name: "Sebastianus", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "septimius_severus", name: "Septimius Severus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "severus_alexander", name: "Severus Alexander", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["alexander severus"]) }),
  Object.freeze({ id: "severus_ii", name: "Severus II", volumes: Object.freeze(["VI"]), aliases: Object.freeze(["flavius valerius severus"]) }),
  Object.freeze({ id: "sextus_martinianus", name: "Martinianus", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["sextus marcius martinianus"]) }),
  Object.freeze({ id: "sponsianus", name: "Sponsianus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "sulla", name: "Sulla", volumes: Object.freeze(["II"]), aliases: Object.freeze(["lucius cornelius sulla", "lucius cornelius sulla felix"]) }),
  Object.freeze({ id: "tacitus", name: "Tacitus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["marcus claudius tacitus"]) }),
  Object.freeze({ id: "tetricus_i", name: "Tetricus I", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "tetricus_ii", name: "Tetricus II", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "theodora", name: "Theodora", volumes: Object.freeze(["VIII"]), aliases: Object.freeze(["flavia maximiana theodora"]) }),
  Object.freeze({ id: "theodosius_i", name: "Theodosius I", volumes: Object.freeze(["IX"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "theodosius_ii", name: "Theodosius II", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "tiberius", name: "Tiberius", volumes: Object.freeze(["I (2nd edition)", "II", "II, Part 1 (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "titus", name: "Titus", volumes: Object.freeze(["II", "II, Part 1 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "trajan", name: "Trajan", volumes: Object.freeze(["II", "II, Part 3 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "trajan_decius", name: "Trajan Decius", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["decius"]) }),
  Object.freeze({ id: "trebonianus_gallus", name: "Trebonianus Gallus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "ulpia_severina", name: "Ulpia Severina", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "uranius_antoninus", name: "Uranius Antoninus", volumes: Object.freeze(["IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "vabalathus", name: "Vabalathus", volumes: Object.freeze(["V"]), aliases: Object.freeze(["lucius iulius septimius vaballatus aphenodorus"]) }),
  Object.freeze({ id: "valens", name: "Valens", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["flavius valens"]) }),
  Object.freeze({ id: "valentinian_i", name: "Valentinian I", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["valentinianus i"]) }),
  Object.freeze({ id: "valentinian_ii", name: "Valentinian II", volumes: Object.freeze(["IX"]), aliases: Object.freeze(["valentinianus ii"]) }),
  Object.freeze({ id: "valentinian_iii", name: "Valentinian III", volumes: Object.freeze(["X"]), aliases: Object.freeze(["valentinianus iii"]) }),
  Object.freeze({ id: "valerian", name: "Valerian", volumes: Object.freeze(["V"]), aliases: Object.freeze(["valerianus"]) }),
  Object.freeze({ id: "valerian_ii", name: "Valerian II", volumes: Object.freeze(["V"]), aliases: Object.freeze(["valerianus"]) }),
  Object.freeze({ id: "valerius_valens", name: "Valerius Valens", volumes: Object.freeze(["VII"]), aliases: Object.freeze(["aurelius valerius valens"]) }),
  Object.freeze({ id: "vespasian", name: "Vespasian", volumes: Object.freeze(["II", "II, Part 1 (2nd edition)", "IV"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "vetranio", name: "Vetranio", volumes: Object.freeze(["VIII"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "victorinus", name: "Victorinus", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "vitellius", name: "Vitellius", volumes: Object.freeze(["I (2nd edition)"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "volusian", name: "Volusian", volumes: Object.freeze(["IV"]), aliases: Object.freeze(["gaius vibius volusianus", "volusianus"]) }),
  Object.freeze({ id: "zeno", name: "Zeno", volumes: Object.freeze(["X"]), aliases: Object.freeze([]) }),
  Object.freeze({ id: "zenobia", name: "Zenobia", volumes: Object.freeze(["V"]), aliases: Object.freeze([]) }),
]);

// The modern name Nomisma gives each RIC VI-IX mint section, in English only. A mint whose concept carries no English name but the one RIC
// files it under has no alias here, and none was invented for it.
export const RIC_MINTS = Object.freeze([
  Object.freeze({ id: "ambianum", section: "Amiens", aliases: Object.freeze(["ambianum"]) }),
  Object.freeze({ id: "antiocheia_syria", section: "Antioch", aliases: Object.freeze(["antioch, syria", "antiokheia pros oronten"]) }),
  Object.freeze({ id: "constantinople", section: "Constantinople", aliases: Object.freeze(["istanbul"]) }),
  Object.freeze({ id: "cyzicus", section: "Cyzicus", aliases: Object.freeze(["kyzikos"]) }),
  Object.freeze({ id: "nicomedia", section: "Nicomedia", aliases: Object.freeze(["nikomedia"]) }),
  Object.freeze({ id: "serdica", section: "Serdica", aliases: Object.freeze(["serdika"]) }),
  Object.freeze({ id: "thessalonica", section: "Thessalonica", aliases: Object.freeze(["thessalonika"]) }),
  Object.freeze({ id: "treveri", section: "Treveri", aliases: Object.freeze(["trier"]) }),
]);
